#!/bin/bash
echo "-----------"
echo "POST COMMIT"

: '
branch=$(git branch --show-current)

if [[ $branch == "main" ]]; then
    echo "Adding tag"
    v="v"
    num=$(jq .version data/version/version.json -r)
    version=$v$num
    echo $version

    git tag $version
    git push origin $version
fi
'
echo "-----------"
