#!/bin/bash

echo "PRE COMMIT"

echo "Updating patch to:"
./data/version/increase.sh 0 0 1
jq .version data/version/version.json -r

# Because he files change, we need to add it again before the commit
git add data/version/version.json
