# Use to automaticlly create new releases

name: Auto Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get tag name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Set upload URL as environment variable
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

  upload-license:
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - name: Clone and check out branch
        uses: actions/checkout@v2

      - name: Upload License
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./LICENSE
          asset_name: LICENSE
          asset_content_type: text/plain

  fedora-build:
    needs: create-release

    container: registry.fedoraproject.org/fedora-minimal:latest
    runs-on: ubuntu-latest

    steps:
      - name: Installing git dependencies
        run: dnf -y install git tar

      - name: Clone and check out branch
        uses: actions/checkout@v2

      - name: Installing program dependencies
        run: dnf -y install gcc make jq "pkgconfig(libcjson)" "pkgconfig(libpcap)"

      - name: Compiling
        run: make release

      - name: Upload Fedora executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./hawk
          asset_name: hawk-${{ env.TAG_NAME }}.fedora.x86-x64
          asset_content_type: application/x-executable

  ubuntu-build:
    needs: create-release

    runs-on: ubuntu-latest

    steps:
      - name: Updating OS
        run: sudo apt update && sudo apt upgrade -y

      - name: Installing git dependencies
        run: sudo apt -y install git

      - name: Clone and check out branch
        uses: actions/checkout@v2

      - name: Installing program dependencies
        run: sudo apt -y install git gcc make jq libcjson-dev libpcap-dev

      - name: Compiling with release flags
        run: make release

      - name: Upload Ubuntu executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./hawk
          asset_name: hawk-${{ env.TAG_NAME }}.ubuntu.x86-x64
          asset_content_type: application/x-executable
