name: Fedora Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  fedora-build:
    container: registry.fedoraproject.org/fedora-minimal:latest
    runs-on: ubuntu-latest

    steps:
      - name: Installing git dependencies
        run: dnf -y install git tar

      - name: Clone and check out branch
        uses: actions/checkout@v4

      - name: Installing program dependencies
        run: dnf -y install gcc make "pkgconfig(libcjson)" "pkgconfig(libpcap)"

      - name: Compiling
        run: make release
