name: Fedora Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  fedora-build:
    container: registry.fedoraproject.org/fedora-minimal:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installing dependencies
        run: sudo dnf -y install git tar gcc make "pkgconfig(libcjson)" "pkgconfig(libpcap)"

      - name: Compiling
        run: make release
