name: Ubuntu Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Updating OS
        run: sudo apt update && sudo apt upgrade -y

      - name: Installing git dependencies
        run: sudo apt -y install git

      - name: Clone and check out branch
        uses: actions/checkout@v4

      - name: Installing program dependencies
        run: sudo apt -y install git gcc make libcjson-dev libpcap-dev

      - name: Compiling
        run: make release
